def output_xml(sys):
    print("output: forcefield.xml")
    mass = sys[0]
    path = "./forcefield.xml"
    f = open(path, 'w')
    f.write("<ForceField>\n")
    f.write(" <AtomTypes>\n")

    f.write(f"  <Type name=\"ru1\" class=\"P\" element=\"P\" mass=\"{mass}\"/>\n")
    f.write(f"  <Type name=\"ru2\" class=\"P\" element=\"P\" mass=\"{mass}\"/>\n")
    f.write(f"  <Type name=\"ru3\" class=\"P\" element=\"P\" mass=\"{mass}\"/>\n")
    f.write(" </AtomTypes>\n")
    f.write(" <Residues>\n")
    f.write("  <Residue name=\"Pm\">\n")
    f.write(f"   <Atom name=\"P1\" type=\"ru1\"/>\n")
    f.write(f"   <Atom name=\"P2\" type=\"ru2\"/>\n")
    f.write(f"   <Atom name=\"P3\" type=\"ru3\"/>\n")
    f.write(f"   <Bond atomName1=\"P1\" atomName2=\"P2\"/>\n")
    f.write(f"   <Bond atomName1=\"P2\" atomName2=\"P3\"/>\n")
    f.write(f"   <ExternalBond atomName=\"P1\"/>\n")
    f.write(f"   <ExternalBond atomName=\"P3\"/>\n")
    f.write("  </Residue>\n")
    f.write("  <Residue name=\"CPm\">\n")
    f.write(f"   <Atom name=\"P1\" type=\"ru1\"/>\n")
    f.write(f"   <Atom name=\"P2\" type=\"ru2\"/>\n")
    f.write(f"   <Atom name=\"P3\" type=\"ru3\"/>\n")
    f.write(f"   <Bond atomName1=\"P1\" atomName2=\"P2\"/>\n")
    f.write(f"   <Bond atomName1=\"P2\" atomName2=\"P3\"/>\n")
    f.write(f"   <ExternalBond atomName=\"P3\"/>\n")
    f.write("  </Residue>\n")
    f.write(" </Residues>\n")
    f.write("</ForceField>")
    f.close()